### ISSUE TITLE
Status for TYPO3 v11

### ISSUE THREAD

**Issue by xperseguers** [xperseguers/t3ext-ig_ldap_sso_auth#133]
To make it clear: support for v11 is ongoing.

Please test this git repository and report problems if anything is found.

There are currently no planned release. Development on this project is based on free time as not currently in need of support for TYPO3 v11. Feel free to suggest sponsoring if you need some more reactive work on it.

Thanks.

**Comment by afle** [comment]
For us it's very important since we are planning to upgrade all our TYPO3 installations to version 11. 
What are the options for support/sponsoring you to finish this feature?

**Comment by xperseguers** [comment]
Just tested both backend and frontend authentication in v11 and it worked for me.

> Currently version 3.7-dev is not working on TYPO3 v11.5.10.

Maybe describe what is not working...

**Comment by afle** [comment]
You have to import users manually, otherwise log message:
`Login-attempt from x.x.x.x, username '<usernam>' not found!`

If imported, logon is not possible:
`Login-attempt from  x.x.x.x, username '<username>', no suitable hash method found!`


What surprises me: column _be_users.tx_igldapssoauth_dn_ is empty even when imported the users.

**Comment by xperseguers** [comment]
That's the result of using the demo LDAP server depicted in the documentation, with latest master branch and TYPO3 v11 (`be_users`):

![image](https://user-images.githubusercontent.com/646805/172064891-c158425a-c1f1-4728-bb90-003990e58feb.png)

When I configure the extension to allow users not yet imported (`backend.TYPO3BEUserExist`) and delete (!) every LDAP-related row and try again with `newton`/`password`, I just found a PHP warning which I fixed and will debug why (I can reproduce) an not yet-imported user cannot actually log in as you found. However, imported users work fine for me.

**Comment by xperseguers** [comment]
somehow the auto-created be_user is marked as "disabled", thus cannot authenticate!

**Comment by afle** [comment]
That's a user we imported manually, since it wasn't done by the extension:

```
 select * from be_users \G;
                 uid: 8
                 pid: 0
              tstamp: 1653912255
              crdate: 1653912255
           cruser_id: 0
             deleted: 0
             disable: 0
           starttime: 0
             endtime: 0
         description: NULL
            username: <username>
              avatar: 0
            password: <some hash>
               admin: 0
           usergroup: 2
                lang: default
               email: <email@adress>
      db_mountpoints: NULL
             options: 3
            realName: <real name of user>
            userMods: NULL
   allowed_languages:
                  uc: NULL
    file_mountpoints: NULL
    file_permissions: readFolder,writeFolder,addFolder,renameFolder,moveFolder,deleteFolder,readFile,writeFile,addFile,renameFile,replaceFile,moveFile,copyFile,deleteFile
     workspace_perms: 1
            TSconfig: NULL
           lastlogin: 0
        workspace_id: 0
                 mfa: NULL
      category_perms: NULL
password_reset_token:
 tx_igldapssoauth_dn:
 tx_igldapssoauth_id: 2

```
